### ISSUE TITLE
[6월 17일 - 6월 19일] 황지수 TODO

### ISSUE THREAD

**Issue by JiSoo-Hwang** [JiSoo-Hwang/MungHub#1]
6월 17일 (1일차)

- [ ] 강아지 유치원 공공 데이터 csv 파일 지도 api 활용해서 지도에 띄우는 작업하기
- [ ] 테이블 스크립트 실행해보고, 수정이 필요한 사항 수정하기 (ERD도 함께 수정할 것)
- [ ] 유치원 등록 상담 신청서 jsp 파일 만들기

6월 18일(2일차)

- [ ] (지도를 띄우는 작업을 성공했다면) 클릭하면 상세 정보 모달 뜰 수 있도록 작업하기
- [ ] 유치원 등록 상담 신청 조회 jsp 파일 만들기

6월 19일(3일차)

- [ ] 유치원 등록 상담 승인/거절 기능 구현
